apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: monokube
immutable: true
data:
  POSTGRES_PASSWORD: ''
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: monokube
  labels:
    app: postgres
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:16.3
          envFrom:
            - secretRef:
                name: postgres
          livenessProbe:
            exec:
              command: [ "CMD-SHELL", "pg_isready -U postgres" ]
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 5432
              name: tcp
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: run
              mountPath: /var/run/postgresql
      volumes:
        - name: run
          emptyDir:
            sizeLimit: 1Ki
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ 'ReadWriteOnce' ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: monokube
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: tcp
  selector:
    app: postgres
---
