domains:
  root: mk.dokevy.io

kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: 7.6.1
  ui:
    image:
      repository: provectuslabs/kafka-ui
      tag: v0.7.2

minio:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-06-13T22-53-53Z

postgres:
  image:
    repository: postgres
    tag: "16.3"


################################################################
##
##  OpenTelemetry
##

##  ==== Agent ====

otel_agent:

  fullnameOverride: otel

  mode: daemonset

  image:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.101.0

  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
      storeCheckpoints: true
    hostMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
      extractAllPodAnnotations: true
    kubeletMetrics:
      enabled: true

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: delete
            key: kubectl_kubernetes_io_last_applied_configuration
          - action: insert
            key: opentelemetry
            value: daemonset
    # does not work on dependencies with null to unset default value
    # receivers:
    #   jaeger: null
    #   prometheus: null
    #   zipkin: null
    service:
      pipelines:
        logs:
          exporters:
            - otlp
          processors:
            - k8sattributes
            - attributes
            - memory_limiter
            - batch
        metrics:
          exporters:
            - otlp
          processors:
            - k8sattributes
            - attributes
            - memory_limiter
            - batch
        traces:
          exporters:
            - otlp
          processors:
            - k8sattributes
            - attributes
            - memory_limiter
            - batch
      telemetry:
        logs:
          level: warn



##  ==== Collector ====

otel_collector:

  fullnameOverride: otel-collector

  mode: deployment

  image:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.102.1

  replicaCount: 1

  presets:
    kubernetesEvents:
      enabled: true
    clusterMetrics:
      enabled: true

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: insert
            key: opentelemetry
            value: deployment
    receivers:
      jaeger:
      otlp:
      prometheus:
      zipkin:
    service:
      pipelines:
        logs:
          exporters:
            - otlp
        traces:
          exporters:
            - otlp
      telemetry:
        logs:
          level: warn

##  ==== Kafka Consumer ====

otel_consumer:

  fullnameOverride: otel-consumer

  mode: deployment

  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.102.1

  replicaCount: 1

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: insert
            key: opentelemetry
            value: deployment
    receivers:
      jaeger:
      otlp:
      prometheus:
      zipkin:
    service:
      pipelines:
        logs:
          exporters:
            - otlp
        traces:
          exporters:
            - otlp
      telemetry:
        logs:
          level: warn
