global:
  labels:
    org: home

domains:
  root: mk.dokevy.io

kafka:
  image:
    repository: confluentinc/cp-kafka
    tag: 7.6.1
  ui:
    image:
      repository: provectuslabs/kafka-ui
      tag: v0.7.2

minio:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-06-13T22-53-53Z

postgres:
  image:
    repository: postgres
    tag: "16.3"


################################################################
##
##  OpenTelemetry
##

##  ==== Agent ====

otel_agent:

  fullnameOverride: otel

  mode: daemonset

  namespaceOverride: kube-system

  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
      storeCheckpoints: true
    hostMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
      extractAllPodAnnotations: true
    kubeletMetrics:
      enabled: true

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: delete
            key: kubectl_kubernetes_io_last_applied_configuration
          - action: insert
            key: opentelemetry
            value: daemonset
    receivers:
      jaeger: null
      otlp: null
      prometheus: null
      zipkin: null
    service:
      pipelines:
        logs:
          exporters:
            - otlp
          processors:
            - k8sattributes
            - attributes
            - memory_limiter
            - batch
          receivers: []
        metrics:
          exporters:
            - otlp
          processors:
            - k8sattributes
            - attributes
            - memory_limiter
            - batch
          receivers: []
          #   - otlp
        traces: null
          # exporters:
          #   - otlp
          # processors:
          #   - k8sattributes
          #   - attributes
          #   - memory_limiter
          #   - batch
          # receivers: []
          # #   - otlp
      telemetry:
        logs:
          level: warn

  image:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.104.0

  serviceAccount:
    create: false
    name: otel-collector

  ports:
    otlp:
      enabled: false
    otlp-http:
      enabled: false
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  service:
    enabled: false

##  ==== Collector ====

otel_collector:

  fullnameOverride: otel-collector

  mode: deployment

  namespaceOverride: kube-system

  replicaCount: 1

  presets:
    kubernetesEvents:
      enabled: true
    clusterMetrics:
      enabled: true

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: insert
            key: opentelemetry
            value: deployment
    receivers:
      jaeger: null
      otlp: null
      prometheus: null
      zipkin: null
    service:
      pipelines:
        logs:
          exporters:
            - otlp
        traces:
          exporters:
            - otlp
      telemetry:
        logs:
          level: warn

  image:
    repository: otel/opentelemetry-collector-k8s
    tag: 0.104.0

  serviceAccount:
    create: false
    name: otel-collector

  ports:
    otlp:
      enabled: false
    otlp-http:
      enabled: false
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  service:
    enabled: false

##  ==== Kafka Consumer ====

otel_consumer:

  fullnameOverride: otel-consumer

  mode: deployment

  namespaceOverride: kube-system

  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.104.0

  replicaCount: 1

  config:
    exporters:
      otlp:
        endpoint: otlp.dokevy.io:4317
        tls:
          insecure: true
    processors:
      attributes:
        actions:
          - action: insert
            key: opentelemetry
            value: deployment
    receivers:
      jaeger:
      otlp:
      prometheus:
      zipkin:
    service:
      pipelines:
        logs:
          exporters:
            - otlp
        traces:
          exporters:
            - otlp
      telemetry:
        logs:
          level: warn
